name: Dev CI/CD (SSH Deployment)

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} # AWS account id
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }} # full ECR URI from Terraform
  EC2_USER: ec2-user # default user for EC2
  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} # private key for SSH to EC2
  EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }} # public IP or DNS of your EC2

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

  versioning:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      new_version: ${{ steps.bump.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump semantic version
        id: bump
        run: ./scripts/bump-version.sh

  push:
    runs-on: ubuntu-latest
    needs: versioning

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/dev-github-oidc-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        run: |
          VERSION=${{ needs.versioning.outputs.new_version }}
          echo "Using ECR registry: $ECR_REGISTRY"

          docker build -t $ECR_REGISTRY:$VERSION -t $ECR_REGISTRY:latest .
          docker push $ECR_REGISTRY:$VERSION
          docker push $ECR_REGISTRY:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push
    env:
      VERSION: ${{ needs.versioning.outputs.new_version }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Copy repo to EC2
        run: |
          scp -i ~/.ssh/id_rsa -r . ${EC2_USER}@${EC2_HOST}:/home/ec2-user/app

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ${EC2_USER}@${EC2_HOST} "
            cd /home/ec2-user/app
            export ECR_REGISTRY=$ECR_REGISTRY
            export VERSION=$VERSION
            docker-compose pull
            docker-compose up -d --build
          "

  tag_release:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push Git tag
        run: |
          VERSION=${{ needs.versioning.outputs.new_version }}
          git tag $VERSION
          git push origin $VERSION
---
##########################################
name: CI + Terraform + Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Detect infra changes
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ steps.filter.outputs.infra }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for folder changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            infra:
              - 'infrastructure/terraform/**'

  # Step 2: Terraform Apply
  terraform:
    needs: filter-changes
    runs-on: ubuntu-latest
    if: needs.filter-changes.outputs.infra_changed == 'true'
    environment: stage
    outputs:
      ecr_url: ${{ steps.collect.outputs.ecr_url }}
      ec2_ip: ${{ steps.collect.outputs.ec2_ip }}

    steps:
      - uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Init Terraform
      - name: Terraform Init
        working-directory: infrastructure/terraform
        run: terraform init -upgrade

      # Select/Create stage workspace
      - name: Select Terraform Workspace
        working-directory: infrastructure/terraform
        run: |
          terraform workspace select stage || terraform workspace new stage

      # Terraform Apply
      - name: Terraform Apply
        working-directory: infrastructure/terraform
        env:
          TF_IN_AUTOMATION: true
        run: terraform apply -auto-approve -input=false

      # Collect outputs
      - name: Collect outputs
        id: collect
        working-directory: infrastructure/terraform
        run: |
          echo "ecr_url=$(terraform output -raw ecr_repo_uri)" >> "$GITHUB_OUTPUT"
          echo "ec2_ip=$(terraform output -raw web_instance_public_ip)" >> "$GITHUB_OUTPUT"

  # Step 3: Deploy to EC2
  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    environment: stage
    env:
      ECR_REGISTRY: ${{ needs.terraform.outputs.ecr_url }}
      HOSTNAME: ${{ needs.terraform.outputs.ec2_ip }}
      USER_NAME: ubuntu
      PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      VERSION: ${{ needs.versioning.outputs.new_version || 'v0.0.0' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH key
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key

      - name: Copy repo to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key -r . ${USER_NAME}@${HOSTNAME}:/home/ubuntu/app

      - name: Deploy via SSH
        run: |

          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            aws ecr get-login-password --region us-east-1 \
              | docker login --username AWS --password-stdin ${ECR_REGISTRY}

            cd /home/ubuntu/app/app
            export ECR_REGISTRY=$ECR_REGISTRY
            export VERSION=$VERSION

            # Build and run Docker
            docker build -t $ECR_REGISTRY:$VERSION .
            docker stop app || true
            docker rm app || true
            docker run -d -p 8080:80 --name app $ECR_REGISTRY:$VERSION
          "
