name: CI

on:
  push:
    branches:
      - release/**
    paths:
      - "app/**"

  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ENVIRONMENT: ${{ github.event_name == 'workflow_dispatch'
    && github.event.inputs.environment
    || (github.ref_name == 'release/dev' && 'dev'
    || github.ref_name == 'release/stage' && 'stage'
    || 'prod') }}

permissions:
  contents: write

jobs:
  # Step 1: Detect if app changed to avoid building
  filter:
    runs-on: ubuntu-latest
    outputs:
      app_changed: ${{ steps.filter.outputs.app }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for folder changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            app:
              - 'app/**'
          base: ${{ github.event.before }}

  # Step 2: Download TF state from S3 and save outputs as artifact
  tf-outputs:
    runs-on: ubuntu-latest
    needs: filter
    if: |
      needs.filter.outputs.app_changed == 'true' &&
      (
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
        (github.event_name == 'push' || github.event_name == 'workflow_run')
      )

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download Terraform state
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 cp "s3://$AWS_ACCOUNT_ID-app-dev/env:/$ENVIRONMENT/networking/terraform.tfstate" terraform.tfstate

      - name: Extract outputs -> file
        run: |
          jq -r '{ecr_url: .outputs.ecr_repo_uri.value, ec2_ip: .outputs.web_instance_public_ip.value}' terraform.tfstate > tf-outputs.json
          echo "Extracted terraform outputs:"
          cat tf-outputs.json

      - name: Upload TF outputs artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-outputs
          path: tf-outputs.json

  # CI Build
  build:
    runs-on: ubuntu-latest
    needs: filter
    if: |
      needs.filter.outputs.app_changed == 'true' &&
      (
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
        (github.event_name == 'push' || github.event_name == 'workflow_run')
      )

    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - run: npm ci
      - run: npm run build

  # Semantic versioning
  versioning:
    runs-on: ubuntu-latest
    needs: filter
    if: |
      needs.filter.outputs.app_changed == 'true' &&
      (
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
        (github.event_name == 'push' || github.event_name == 'workflow_run')
      )

    outputs:
      new_version: ${{ steps.bump.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: chmod +x ./.github/actions/scripts/bump-version.sh
      - id: bump
        run: ./.github/actions/scripts/bump-version.sh

  # Build and push Docker image to ECR
  push:
    runs-on: ubuntu-latest
    needs: [versioning, tf-outputs, build]
    env:
      VERSION: ${{ needs.versioning.outputs.new_version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Load TF Outputs
        uses: ./.github/actions/load-tf-outputs

      - name: Build, tag, and push image to ECR
        run: |
          echo "ECR_REGISTRY=$ECR_URL"
          echo "VERSION=$VERSION"
          docker build -t $ECR_URL:$VERSION ./app
          docker push $ECR_URL:$VERSION

  # Create Git tag
  tag_release:
    runs-on: ubuntu-latest
    needs: [push, versioning]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: |
          VERSION=${{ needs.versioning.outputs.new_version }}
          git tag $VERSION
          git push origin $VERSION

  # Deploy to EC2
  deploy:
    runs-on: ubuntu-latest
    needs: [push, versioning]
    env:
      VERSION: ${{ needs.versioning.outputs.new_version }}
      USER_NAME: ubuntu

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load TF Outputs
        uses: ./.github/actions/load-tf-outputs

      - name: Deploy to EC2
        uses: ./.github/actions/deploy-to-ec2
        with:
          private-key: ${{ secrets.EC2_SSH_KEY }}
          username: ubuntu
          version: ${{ env.VERSION }}
          ecr-url: ${{ env.ECR_URL }}
          aws-account-id: ${{ env.AWS_ACCOUNT_ID }}
          ec2-ip: ${{ env.EC2_IP }}

  #---------------------TESTING FOR ROLLBACK-----------------------------

  #smoke test
  smoke_test:
    runs-on: ubuntu-latest
    needs: deploy
    outputs:
      smoke_result: ${{ steps.smoke.outputs.result }}
    steps:
      - uses: actions/checkout@v4

      - name: Load TF Outputs
        uses: ./.github/actions/load-tf-outputs

      - name: Make smoke script executable
        run: chmod +x ./.github/actions/scripts/smoke-test.sh

      - name: Run smoke script
        id: smoke
        run: .github/actions/scripts/smoke-test.sh "$EC2_IP" "8080"

  #rollback verions
  rollback_versioning:
    runs-on: ubuntu-latest
    needs: smoke_test
    if: needs.smoke_test.outputs.smoke_result == 'false'

    outputs:
      rollback_version: ${{ steps.rollback.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make rollback script executable
        run: chmod +x ./.github/actions/scripts/rollback-version.sh

      - name: Run rollback script
        id: rollback
        run: |
          ./.github/actions/scripts/rollback-version.sh

  # rollback Deploy to EC2
  rollback_deploy:
    runs-on: ubuntu-latest
    needs: rollback_versioning
    env:
      VERSION: ${{ needs.rollback_versioning.outputs.rollback_version}}
      USER_NAME: ubuntu

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load TF Outputs
        uses: ./.github/actions/load-tf-outputs

      - name: Deploy to EC2
        uses: ./.github/actions/deploy-to-ec2
        with:
          private-key: ${{ secrets.EC2_SSH_KEY }}
          username: ubuntu
          version: ${{ env.VERSION }}
          ecr-url: ${{ env.ECR_URL }}
          aws-account-id: ${{ env.AWS_ACCOUNT_ID }}
          ec2-ip: ${{ env.EC2_IP }}

  # Create rollback Git tag
  tag_release_rollback:
    runs-on: ubuntu-latest
    needs: [rollback_deploy, rollback_versioning]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: |
          VERSION=${{ needs.rollback_versioning.outputs.rollback_version}}
          ROLLBACK_TAG="rollback-$VERSION"
          echo "Creating rollback tag: $ROLLBACK_TAG"
          git tag $ROLLBACK_TAG
          git push origin $ROLLBACK_TAG
