name: Dev CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} # AWS account id
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }} # full ECR URI from Terraform
  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} # private key for SSH to EC2
  EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }} # public IP from terraform test feat

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

  #creates semantic versioning
  versioning:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      new_version: ${{ steps.bump.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make bump script executable
        run: chmod +x ./scripts/bump-version.sh

      - name: Bump semantic version
        id: bump
        run: ./scripts/bump-version.sh

  #build and push docker image to ecr
  push:
    runs-on: ubuntu-latest
    needs: versioning

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        run: |
          VERSION=${{ needs.versioning.outputs.new_version }}
          echo "Using ECR registry: $ECR_REGISTRY"

          docker build -t $ECR_REGISTRY:$VERSION ./app
          docker push $ECR_REGISTRY:$VERSION

  #create tag
  tag_release:
    runs-on: ubuntu-latest
    needs: [push, versioning]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN  }}

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push Git tag
        run: |
          VERSION=${{ needs.versioning.outputs.new_version }}
          git tag $VERSION
          git push origin $VERSION

  #deploy to ec2
  deploy:
    runs-on: ubuntu-latest
    needs: [push, versioning]
    env:
      VERSION: ${{ needs.versioning.outputs.new_version }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      HOSTNAME: ${{ secrets.EC2_PUBLIC_IP }}
      USER_NAME: ubuntu

    steps:
      - name: Setup SSH key
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

      - name: Copy repo to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key -r . ${USER_NAME}@${HOSTNAME}:/home/ubuntu/app

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            cd /home/ubuntu/app
            export ECR_REGISTRY=$ECR_REGISTRY
            export VERSION=$VERSION
            docker-compose pull
            docker-compose up -d --build
          "
