name: CI + Terraform

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
  ENVIRONMENT: stage

permissions:
  contents: write

jobs:
  # Step 1: Detect infra changes
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ steps.filter.outputs.infra }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for folder changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            infra:
              - 'infrastructure/terraform/**'

  # Step 2: Terraform Apply
  terraform:
    needs: filter-changes
    runs-on: ubuntu-latest
    if: needs.filter-changes.outputs.infra_changed == 'true'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Terraform Init
        working-directory: infrastructure/terraform
        run: terraform init -upgrade
      - name: Select Terraform Workspace
        working-directory: infrastructure/terraform
        run: |
          terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT
      - name: Terraform Apply
        working-directory: infrastructure/terraform
        env:
          TF_IN_AUTOMATION: true
        run: terraform apply -auto-approve -input=false -var="ENV_PREFIX=$ENVIRONMENT"

  # Step 3: Download TF state from S3 and extract outputs
  tf-outputs:
    runs-on: ubuntu-latest
    outputs:
      ecr_url: ${{ steps.extract.outputs.ECR_URL }}
      ec2_ip: ${{ steps.extract.outputs.EC2_IP }}

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download Terraform state
        run: aws s3 cp "s3://850502433430-app-dev/env:/stage/networking/terraform.tfstate" terraform.tfstate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Extract outputs
        id: extract
        run: |
          ECR_URL=$(jq -r '.outputs.ecr_repo_uri.value' terraform.tfstate)
          EC2_IP=$(jq -r '.outputs.web_instance_public_ip.value' terraform.tfstate)
          echo "ECR_URL=$ECR_URL" >> "$GITHUB_OUTPUT"
          echo "EC2_IP=$EC2_IP" >> "$GITHUB_OUTPUT"

      - name: Debug extracted outputs
        run: |
          echo "ECR_URL=${{ steps.extract.outputs.ecr_url }}"
          echo "EC2_IP=${{ steps.extract.outputs.ec2_ip }}"

  # CI Build
  build:
    runs-on: ubuntu-latest
    needs: tf-outputs
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      - run: npm ci
      - run: npm run build

      - name: Debug extracted outputs
        run: |
          echo "ECR_URL=${{ steps.tf-outputs.outputs.ecr_url }}"
          echo "EC2_IP=${{ steps.tf-outputs.outputs.ec2_ip }}"

  # Semantic versioning
  versioning:
    runs-on: ubuntu-latest
    needs: [build, tf-outputs]
    outputs:
      new_version: ${{ steps.bump.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: chmod +x ./scripts/bump-version.sh
      - id: bump
        run: ./scripts/bump-version.sh

      - name: Debug extracted outputs
        run: |
          echo "ECR_URL=${{ steps.extract.outputs.ECR_URL }}"
          echo "EC2_IP=${{ steps.extract.outputs.EC2_IP }}"

  # Build and push Docker image to ECR
  push:
    runs-on: ubuntu-latest
    needs: [versioning, tf-outputs]
    env:
      VERSION: ${{ needs.versioning.outputs.new_version }}
      ECR_REGISTRY: ${{ needs.tf-outputs.outputs.ecr_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image
        run: |
          echo "ECR_REGISTRY=$ECR_REGISTRY"
          echo "VERSION=$VERSION"
          docker build -t $ECR_REGISTRY:$VERSION ./app
          docker push $ECR_REGISTRY:$VERSION

  # Create Git tag
  tag_release:
    runs-on: ubuntu-latest
    needs: [push, versioning]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: |
          VERSION=${{ needs.versioning.outputs.new_version }}
          git tag $VERSION
          git push origin $VERSION

  # Deploy to EC2
  deploy:
    runs-on: ubuntu-latest
    needs: [push, versioning, tf-outputs]
    env:
      VERSION: ${{ needs.versioning.outputs.new_version }}
      ECR_REGISTRY: ${{ needs.tf-outputs.outputs.ecr_url }}
      PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      HOSTNAME: ${{ needs.tf-outputs.outputs.ec2_ip }}
      USER_NAME: ubuntu
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
      - run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            aws ecr get-login-password --region us-east-1 \
              | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com

            docker pull \$ECR_REGISTRY:\$VERSION
            docker ps -q --filter 'name=app' | grep -q . && docker stop app && docker rm app
            docker run -d --name app -p 8080:80 \$ECR_REGISTRY:\$VERSION
          "
