# Step 3: Download TF state from S3 and extract outputs
tf-outputs:
  runs-on: ubuntu-latest
  outputs:
    ecr_url: ${{ steps.extract.outputs.ecr_url }}
    ec2_ip: ${{ steps.extract.outputs.ec2_ip }}

  steps:
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Download Terraform state
      run: aws s3 cp "s3://850502433430-app-dev/env:/stage/networking/terraform.tfstate" terraform.tfstate
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Extract outputs
      id: extract
      run: |
        ECR_URL=$(jq -r '.outputs.ecr_repo_uri.value' terraform.tfstate)
        EC2_IP=$(jq -r '.outputs.web_instance_public_ip.value' terraform.tfstate)
        echo "ecr_url=$ECR_URL" >> "$GITHUB_OUTPUT"
        echo "ec2_ip=$EC2_IP" >> "$GITHUB_OUTPUT"

    - name: Debug extracted outputs
      run: |
        echo "ECR_URL=${{ steps.extract.outputs.ecr_url }}"
        echo "EC2_IP=${{ steps.extract.outputs.ec2_ip }}"

# CI Build
test:
  runs-on: ubuntu-latest
  needs: tf-outputs
  steps:
    - name: Debug extracted outputs
      run: |
        echo "ECR_URL=${{ needs.tf-outputs.outputs.ecr_url }}"
        echo "EC2_IP=${{ needs.tf-outputs.outputs.ec2_ip }}"
